---
title: "Midterm Assessment"
format: html
editor: visual
---

```{r}
library(ggplot2)
library(dplyr)
```

```{r}
aus = read.table('Australia.txt', header = T)
aus$Year = as.numeric(aus$Year)
aus$Birth = as.numeric(aus$Birth)
aus$Deaths = as.numeric(aus$Deaths)
aus$Population = as.numeric(aus$Population)

netMigrate = c()

for (year in 1921:2020) {
  cur = aus[aus$Year == year, ]
  nextYear = aus[aus$Year == year + 1, ]
  migration = nextYear$Population - cur$Population - cur$Birth + cur$Deaths
  
  netMigrate = c(netMigrate, migration)
}

netMigrate = c(netMigrate, NA)

aus$Migration = netMigrate

ggplot(data = aus) + 
  geom_line(aes(x = Year, y = netMigrate)) + 
  scale_y_continuous(labels = function(x) format(x, scientific = F)) + 
  geom_point(aes(x = 1945, y = -13376.0, color = 'Minimum - 1945')) + 
  geom_point(aes(x = 2008, y = 281158.7, color = 'Maximum - 2008')) + 
  xlab("Net Migration") + ggtitle("Trends in net migration to Australia, 1921-2020")
```

```{r}
aus$PopNew = aus$Population + aus$Birth - aus$Deaths + aus$Migration

aus$PopYear = (aus$PopNew + aus$Population)/2

aus$CGR = (aus$PopNew - aus$Population)/aus$PopYear

aus$CBR = aus$Birth/aus$PopYear

aus$CDR = aus$Deaths/aus$PopYear

aus$CNMR = aus$Migration/aus$PopYear

ggplot(data = aus) + 
  geom_line(aes(x = Year, y = CGR, color = 'Crude Growth Rate')) + 
  geom_line(aes(x = Year, y = CBR, color = 'Crude Birth Rate')) + 
  geom_line(aes(x = Year, y = CDR, color = 'Crude Death Rate')) + 
  geom_line(aes(x = Year, y = CNMR, color = 'Crude Net Migration Rate')) + 
  guides(color = guide_legend(title = "Statistic")) + labs(x = 'Year', y = 'Value') + 
  ggtitle('Time trends of demographic statistics, Australia 1921-2020')
```

```{r}
asfr = read.table('ASFR1.txt', header = T)
asfr$ax = rep(0.5, length(asfr$Age))

japan = select(asfr, Age, Japan, ax)
usa = select(asfr, Age, USA, ax)

japMAC = sum((japan$Japan)*(japan$Age + 0.5))/sum(japan$Japan)
usaMAC = sum((usa$USA) * (usa$Age + 0.5))/sum(usa$USA)

japTFR = sum(japan$Japan)
usaTFR = sum(usa$USA)
```

```{r}
LifeTableMx<-function(mx,sex){
  
  N<-length(mx)
  
  ax<-rep(0.5,N) #this 
  
  if(sex=="m"){
    ax[1]<-ifelse(mx[1]<0.107,0.045+mx[1]*2.684,0.330)}
  if(sex=="f"){
    ax[1]<-ifelse(mx[1]<0.107,0.053+2.800*mx[1],0.350)
  }
  
  # We need the functions to calculate ex from qx
  
  qx <- mx/(1 + (1 - ax)*mx)
  qx[N] <- 1
  
  px<-1-qx
  
  lx<-100000
  
  for(y in 1:(N-1)){          

    lx[y+1] <- lx[y]*px[y]
  }
  
  dx <- lx*qx
  
  Lx <- lx[-1] + ax[-N]*dx[-N] 
  
  Lx[N]<-ifelse(mx[N]>0,lx[N]/mx[N],0)                  
  
  Tx<-c()
  
  for(y in 1:N){
    # Calculate Tx
    Tx[y] <- sum(Lx[y:N])
  }
  
  ex <- Tx/lx 
  
  Age<-12:55             
  ALL<-data.frame(Age,mx,lx,dx,Lx,Tx,ex)
  return(ALL)
}
```

```{r}
japLT = LifeTableMx(japan$Japan, 'f')
```

```{r}
usaLT = LifeTableMx(usa$USA, 'f')
```

```{r}
ggplot() + 
  geom_line(aes(x = japLT$Age, y = japLT$Lx/100000, color = 'Japan')) + 
  geom_line(aes(x = usaLT$Age, y = usaLT$Lx/100000, color = 'USA')) + 
  ggtitle("Proportion of women remaining childless") + labs(x = 'Age', y = 'Proportion of childless women')
```

```{r}
ggplot() + 
  geom_line(aes(x = japLT$Age, y = japLT$dx, color = 'Japan')) + 
  geom_line(aes(x = usaLT$Age, y = usaLT$dx, color = 'USA')) + 
  ggtitle("Change in childbearing") + labs(x = 'Age', y = 'Decrements')
```
