---
title: "Data and Methods - DEMO2002 Assignment 1"
author: "Sreehari Pulickamadhom Sreedhar"
format: html
editor: visual
---

```{r}
#| echo: false
library(ggplot2)
```

## Life Expectancy at Birth

```{r}
#| echo: false
DNK <- read.table('DNKexpPer.txt', skip = 2, header = T) 
SWE <- read.table('SWEexpPer.txt', skip = 2, header = T) 
FIN <- read.table('FINexpPer.txt', skip = 2, header = T) 
ISL <- read.table('ISLexpPer.txt', skip = 2, header = T) 
NOR <- read.table('NORexpPer.txt', skip = 2, header = T)
```

```{r}
#| echo: false
ggplot() + 
  geom_line(data = DNK, mapping = aes(x = Year, y = Total, color = "Denmark")) + 
  geom_line(data = ISL, mapping = aes(x = Year, y = Total, color = "Iceland")) + 
  geom_line(data = NOR, mapping = aes(x = Year, y = Total, color = "Norway")) + 
  geom_line(data = SWE, mapping = aes(x = Year, y = Total, color = "Sweden")) + 
  geom_line(data = FIN, mapping = aes(x = Year, y = Total, color = "Finland")) + 
    labs(colour = "Region") + theme_bw() + 
  ggtitle("Life Expectancy at Birth, Period Data")
  
```

```{r}
#| echo: false
start = 1878
end = 2020

DNK <- DNK[DNK$Year >= 1878 & DNK$Year <= 2020,]
SWE <- SWE[SWE$Year >= 1878 & SWE$Year <= 2020,]
FIN <- FIN[FIN$Year >= 1878 & FIN$Year <= 2020,]
ISL <- ISL[ISL$Year >= 1878 & ISL$Year <= 2020,]
NOR <- NOR[NOR$Year >= 1878 & NOR$Year <= 2020,]
```

```{r}
#| echo: false
Nord = data.frame(Year = 1878:2020,
                  Denmark = DNK$Total, 
                  Finland = FIN$Total, 
                  Iceland = ISL$Total,
                  Norway = NOR$Total,
                  Sweden = SWE$Total)

Nord$Avg <- (Nord$Denmark + Nord$Finland + Nord$Iceland + Nord$Norway + Nord$Sweden)/5
Nord$AvgExclude <- (Nord$Finland + Nord$Iceland + Nord$Norway + Nord$Sweden)/4
```

```{r}
#| echo: false
ggplot(data = Nord) + 
  geom_line(mapping = aes(x = Year, y = Denmark, color = "Denmark")) + 
  geom_line(mapping = aes(x = Year, y = Avg, color = "Nordic Average")) + 
  labs(colour = "Region") + theme_bw() + 
  ggtitle("Life Expectancy at Birth, Period Data (1878 - 2020)")
  
```

## Decomposition into Gap and Trend

#### 5 year moving average decomposition - Denmark

```{r}
#| echo: false
DNKSeries <- ts(data = Nord$Denmark, start = 1, end = 28.6, frequency = 5)

decompDNK <- decompose(DNKSeries)

plot(decompDNK)
```

#### 5 year moving average decomposition - Nordic Average

```{r}
#| echo: false
NordSeries <- ts(data = Nord$AvgExclude, start = 1, end = 28.6, frequency = 5)

decompNord <- decompose(NordSeries)

plot(decompNord)
```

## Male vs Female life expectancy

```{r}
#| echo: false
Nord$MaleAvg <- (DNK$Male + NOR$Male + ISL$Male + SWE$Male + FIN$Male)/5
Nord$FemaleAvg <- (DNK$Female + NOR$Female + ISL$Female + SWE$Female + FIN$Female)/5
```

```{r}
#| echo: false
ggplot() + 
  geom_line(data = DNK, mapping = aes(x = Year, y = Male, color = "Denmark (Male)")) + 
  geom_line(data = DNK, mapping = aes(x = Year, y = Female, color = "Denmark (Female)")) + 
  geom_line(data = Nord, mapping = aes(x = Year, y = MaleAvg, color = "Nordic Average (Male)")) + 
  geom_line(data = Nord, mapping = aes(x = Year, y = FemaleAvg, color = "Nordic Average (Female)")) + 
  labs(colour = "Region") + theme_bw() + 
  ggtitle("Life Expectancy, Male vs. Female, Period Data (1878 - 2020)")
```

## Difference in Male - Female life expectancy at birth

```{r}
#| echo: false
Nord$DNKDiff <- - DNK$Male + DNK$Female
Nord$SWEDiff <- - SWE$Male + SWE$Female
Nord$ISLDiff <- - ISL$Male + ISL$Female
Nord$NORDiff <- - NOR$Male + NOR$Female
Nord$FINDiff <- - FIN$Male + FIN$Female

Nord$DiffAvg <- (Nord$DNKDiff + Nord$NORDiff + Nord$ISLDiff + Nord$FINDiff + Nord$SWEDiff)/5
Nord$DiffAvgExclude <- (Nord$NORDiff + Nord$ISLDiff + Nord$FINDiff + Nord$SWEDiff)/4
```

```{r}
#| echo: false
ggplot(data = Nord) + 
  geom_line(mapping = aes(x = Year, y = DNKDiff, color = "Denmark")) + 
  geom_line(mapping = aes(x = Year, y = DiffAvg, color = "Nordic Average")) + 
  labs(colour = "Region") + theme_bw() + 
  ggtitle("Difference in Life Expectancy (Female - Male), Period Data (1878 - 2020)")
```
